// Generated by the sysprop generator. DO NOT EDIT!

#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace android::sysprop::IncrementalProperties {

std::optional<std::string> enable();

}  // namespace android::sysprop::IncrementalProperties
